table _Measures
	lineageTag: ed429b60-6095-479d-886e-1146d4d8a7c0

	measure 'Total Rows' = ```
			COUNTROWS('DimDate') 
			```
		formatString: #,0
		lineageTag: b6d91921-7a40-49dd-9312-5607f9830d82

	measure 'Total Quarters' = ```
			DISTINCTCOUNT(DimDate[QuarterStart]) 
			```
		formatString: 0
		lineageTag: c06e712b-f04c-4d2b-b6ea-78ef230079d9

	column Value
		isHidden
		formatString: 0
		lineageTag: f0b323c2-96d3-4771-b7ed-d0c29fd9e66b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = ```
				{0} 
				```

	annotation PBI_Id = 3635019512fa42249de503eff5325d3a

